### ISSUE TITLE
About the performance of PCPA on JAAD-beh

### ISSUE THREAD

**Issue by xingchenzhang** [ykotseruba/PedestrianActionBenchmark#10]
Dear authors,

I am wondering if that is possible for you to provide your pretrained model of PCPA on the JAAD-beh dataset?

I have trained this model using the same parameters, however the results I obtained are much worse than what you reported in your paper. I got acc = 0.5, auc = 0.47, f1 = 0.59, precision = 0.6, recall = 0.58. 

I wish to produce some qualitative comparison with PCPA, but it might be unfair (for example maybe I missed something so I do not obtain good performance) to use the PCPA results produced by myself.

Many thanks for your help!
Xingchen

**Comment by ykotseruba** [comment]
Hi Xingchen,
We found some issues with sampling after submitting the final print version. After correcting it the number of samples for training was reduced, so even though the benefits of the hybrid model are still evident, the overall results dropped somewhat. This didn't affect PIE because it's a large dataset, but JAAD is much smaller, especially the behavioural subset.

In general, PCPA is a rather large model for JAAD and fairly difficult to train. For better results I recommend dropping the learning rate to 10-9 or 10-10 and train for 60 epochs. I put a pretrained model for JAAD_beh on Dropbox, the link is [here](https://www.dropbox.com/sh/0ebn884c7vu69pb/AAAgClIYpvQDbD4V7uZkVZ7Ya?dl=0). You can run it using the `test.py` script by providing a path to a pretrained model as a command line argument. Hope this helps.
Yulia

**Comment by xingchenzhang** [comment]
Hi Yulia,

Many thanks for your reply and for sending the pretrained model. However, when I tried to run your model, I got the error 'ValueError: bad marshal data (unknown type code)', which may be because of different versions of Python...I haven't solved this yet.

I also trained PCPA with the learning rate 5.0e-10 for 60 epochs, but the results were even worse...(I didn't use speed, because I found there was no speed in the config.yaml you sent).

I will try again. 

Thanks a lot!
Xingchen

**Comment by ykotseruba** [comment]
Hi Xingchen,
Are you using the docker setup? If not, perhaps, give it a try.
I used Python 3.6.9 to train and save the model.
Yulia

**Comment by xingchenzhang** [comment]
Hi Yulia,

Sorry for the late reply. 

I am not using the docker setup. I will try it at a later time.

Many thanks for your help!
Xingchen

**Comment by jinxing94** [comment]
> Hi Xingchen,
> Are you using the docker setup? If not, perhaps, give it a try.
> I used Python 3.6.9 to train and save the model.
> Yulia
@ykotseruba 
Which TensorFlow version did you use?

**Comment by jinxing94** [comment]
I have the same issue that I cannot load your pretrained mode.
