### ISSUE TITLE
The updated evaluation results

### ISSUE THREAD

**Issue by d-zh** [ykotseruba/PedestrianActionBenchmark#13]
Hi,
   As you mentioned in [https://github.com/ykotseruba/PedestrianActionBenchmark/issues/3#issuecomment-782693588](url), the number of samples in JAAD decreased. Could you please provide the updated evaluation results in paper Table 2, 3?
  Thanks

**Comment by ykotseruba** [comment]
Hi @d-zh,
Table 2 is unchanged, the variation was very insignificant and within the range that we normally got when retraining the models multiple times. 
In Table 3 only the PCPA with both attention modules was hit by the changes because it is the largest model. On JAAD all the best model we have is acc=0.83 auc=0.83 f1=0.64, on JAADbeh acc=0.56 auc=0.56 and f1=0.68. On PIE the results are unchanged.

**Comment by ykotseruba** [comment]
Closed due to inactivity
