### ISSUE TITLE
Questions about the benchmark

### ISSUE THREAD

**Issue by d-zh** [ykotseruba/PedestrianActionBenchmark#7]
Hi,
Your work is excellent and impressive. Establishing a benchmark for pedestrian action prediction is  urgent because many papers use different methods of evaluation. But I have some questions about the benchmark mentioned in paper. 

First, a pedestrian had the intention to cross but he(she) did not cross at last for some reason.  Such samples are set to “Not-crossing”. But at that moment, this pedestrian really wanted to cross the road. Could you explain these samples?

Second, besides pedestrian action prediction, is pedestrian action detection also important?  If a pedestrian is crossing the road, prediction is no meaning but action detection or recognition is necessary. So is necessary to add action detection or recognition in the benchmark?

Thanks!

**Comment by ykotseruba** [comment]
Hi,
Thank you for your comment, I agree with what you said. The reason we focused on action prediction is because it is more important and appears to be more prevalent in the field. A complete benchmark should include intention prediction and action detection in addition to action prediction. The latter is fairly easy to implement and we are working on extending the benchmark in that direction. 
Predicting intention is more difficult because it is not observable and so far this data is available only for the PIE dataset. Also, in the literature, intention is often conflated with action, so there aren't many models that do intention prediction in the sense you mentioned.

**Comment by d-zh** [comment]
Thank you very much for your reply.
